config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  root 'pokemons#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  def self.search(search)
    if search
      search = '%'+search+'%'
      Pokemon.where('name LIKE ?', search).all
    else
      Pokemon.all
    end
  end

  # TO DO refractor this github code
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  #  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    if params[:types].present?
      t = '%'+ params[:types] +'%'
      @pokemons = Pokemon.where('types LIKE ?', t).order("id ASC")
    else
      @pokemons = Pokemon.search(params[:search]).order("id ASC")
    end

    respond_to do |format|
      format.html
      format.csv { send_data @pokemons.to_csv , :disposition => "attachment; filename=pokemon.csv"}
      format.xml { send_data JSON.parse(@pokemons.to_json).to_xml , :disposition => "attachment; filename=pokemon.xml"}
      format.json { send_data @pokemons.to_json , :disposition => "attachment; filename=pokemon.json"}

    end
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
    set_pokemon
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
    set_pokemon
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    set_pokemon
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    set_pokemon
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_pokemon
    @pokemon = Pokemon.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pokemon_params
    params.require(:pokemon).permit(:kanto_id, :name, :types, :shape, :capture_rate, :sprite, :search)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedexkanto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon, local: true) do |form| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :kanto_id %>
    <%= form.number_field :kanto_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :types %>
    <%= form.text_field :types %>
  </div>

  <div class="field">
    <%= form.label :shape %>
    <%= form.text_field :shape %>
  </div>

  <div class="field">
    <%= form.label :capture_rate %>
    <%= form.number_field :capture_rate %>
  </div>

  <div class="field">
    <%= form.label :sprite %>
    <%= form.text_field :sprite %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<table width="100%">
  <th><%= link_to "GRASS", root_path(:types => "Grass") %></th>
  <th><%= link_to "POISON", root_path(:types => "Poison") %></th>
  <th><%= link_to "FIRE", root_path(:types => "Fire") %></th>
  <th><%= link_to "FLYING", root_path(:types => "Flying") %></th>
  <th><%= link_to "WATER", root_path(:types => "Water") %></th>
  <th><%= link_to "BUG", root_path(:types => "Bug") %></th>
  <th><%= link_to "NORMAL", root_path(:types => "Normal") %></th>
  <th><%= link_to "ELECTRIC", root_path(:types => "Electric") %></th>
  <th><%= link_to "FAIRY", root_path(:types => "Fairy") %></th>
  <th><%= link_to "FIGHTING", root_path(:types => "Fighting") %></th>
  <th><%= link_to "PSYCHIC", root_path(:types => "Psychic") %></th>
  <th><%= link_to "ROCK", root_path(:types => "Rock") %></th>
  <th><%= link_to "STEEL", root_path(:types => "Steel") %></th>
  <th><%= link_to "ICE", root_path(:types => "Ice") %></th>
  <th><%= link_to "GHOST", root_path(:types => "Ghost") %></th>
  <th><%= link_to "DRAGON", root_path(:types => "Dragon") %></th>
  <th><%= link_to "Clear", root_path(@pokemon) %></th>
</table>

<img src="https://camo.githubusercontent.com/1a4b11888ddf9f2b7a9353d6b69503e634e8704c/68747470733a2f2f692e696d6775722e636f6d2f415975745a4f462e706e67" style="width:100%">

<%= form_tag(root_path, method: :get) do %>
  <%= text_field_tag(:search, params[:search], size: "175", placeholder: "Search Pokemon") %>
<% end %>

<br>
<table width="33%" align="center">

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td align="center"><img src=<%= pokemon.sprite %>></td>
        <td align="left"><h1><%= link_to pokemon.name.upcase, pokemon %></h1></td>
      </tr>
    <% end %>
    <tr>
      <td align="right"><%= link_to "Download as CSV", root_path(:format => "csv") %></td>
      <td align="center"><%= link_to "Download as XML", root_path(:format => "xml") %></td>
      <td align="left"><%= link_to "Download as JSON", root_path(:format => "json") %></td>
    </tr>
  </tbody>
</table>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<table>

  <tr>
    <td>
      <p>
        <img src=<%= @pokemon.sprite %> width="200">
      </p>
    </td>

    <td>
      <h1>
        <%= @pokemon.name.capitalize %>
      </h1>

      <p>
        <strong>Pokedex ID:</strong>
        <%= @pokemon.kanto_id %>
      </p>

      <p>
        <strong>Type(s):</strong>
        <%= @pokemon.types %>
      </p>

      <p>
        <strong>Shape:</strong>
        <%= @pokemon.shape.capitalize %>
      </p>

      <p>
        <strong>Capture rate:</strong>
        <%= @pokemon.capture_rate %>%
      </p>
    </td>

  </tr>
</table>

<%= link_to 'Back to Pokedex', pokemons_path %>